version: '3.3'
services:
    torrents:
        container_name: torrents
        ports:
            - '3000:3000'
        restart: on-failure
        environment:
            - YGG_USERNAME=your_username
            - YGG_PASSWORD=your_password
            - TRANSMISSION_HOST=localhost
        volumes:
            - './torrents/:/app/torrents/'
        image: 'mozkadocker/torrents:main'

    transmission:
      image: linuxserver/transmission
      container_name: transmission
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
      volumes:
        - ./config:/config
        - ./downloads:/downloads
      ports:
        - 9091:9091
        - 51413:51413
        - 51413:51413/udp
      restart: unless-stopped