name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: mozkadocker/torrents

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:v${GITHUB_RUN_NUMBER}

    - name: Save Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: .

  push:

    name: Log in and Push image to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: image
        path: .

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Push
      run: docker push $IMAGE_NAME:v${GITHUB_RUN_NUMBER}
